### ISSUE TITLE
Two question

### ISSUE THREAD

**Issue by msaezuchile** [SWIPdev/SWIP#8]
Hello:

I have some problems when I run seg2su_clean.m routine. 

First, I am using the data from: https://doi.org/10.15786/M21S3V because the manual link http://wycehg.wygisc.org/sharedData/poleMtnGeophysics/Yellowstone/OPTA_072016_1/Seismic.zip is no available.

I obtain this error:

Dot indexing is not supported for variables of this type.

Error in median (line 26)
        y(I) = nanmedian(w(I).data);

Error in seg2su_clean (line 256)
                    dgx(nroll)=median(diff(gx{i-1}));

How can I fix the problem?

Thank you 

Miguel

**Comment by msaezuchile** [comment]
I resolved the problem. I don't why, but in MATLAB2020 you need to change median to nanmedian.

Best

Miguel

**Comment by spasquet** [comment]
Hi Miguel,
I apologize, for some reason I did not get a notification for your message.
Glad you could find a trick. I'll replace median by nanmedian in the code.

Best
Sylvain
